# Generated by Django 4.2 on 2023-07-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20)),
                ('dob', models.DateField()),
                ('subject', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=80)),
                ('experience', models.CharField(max_length=150)),
                ('mobileNo', models.IntegerField()),
            ],
        ),
    ]
