# Generated by Django 4.2 on 2023-07-24 16:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_attendance_studentresult_notificationstudent_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feedbackstudent',
            managers=[
                ('obects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='feedback_reply',
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
