# Generated by Django 4.2 on 2023-07-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
