# Generated by Django 4.2 on 2023-07-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assign',
            new_name='homework',
        ),
    ]
