# Generated by Django 4.2 on 2023-07-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_rename_assign_assignment_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='homework',
            field=models.TextField(),
        ),
    ]
