# Generated by Django 4.2 on 2023-07-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=20)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='StaffFeedback',
        ),
        migrations.DeleteModel(
            name='StudentFeedback',
        ),
    ]
