# Generated by Django 4.2 on 2023-07-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_feedback_delete_stafffeedback_delete_studentfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('days', models.ImageField(upload_to='')),
                ('leaveReason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('days', models.ImageField(upload_to='')),
                ('leaveReason', models.TextField()),
            ],
        ),
    ]
