# Generated by Django 4.2 on 2023-07-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_studentleave_teacherleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherleave',
            name='days',
            field=models.IntegerField(),
        ),
    ]
