# Generated by Django 4.2 on 2023-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_alter_teacherleave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='days',
            field=models.IntegerField(),
        ),
    ]
