# Generated by Django 4.2 on 2023-07-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_alter_studentleave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
